[package]
name = "walksanator-il-rs"
version = "0.1.0"
edition = "2021"
default-run = "main"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shlex = "1.1.0"
bitvec = "1.0.1"